"""Serves the repository's root `schema.json` as the form generator's data source.

Why:
    The plan (docs/plans/completed/cv-editor-web-app.md) requires the schema-
    driven form editor to read the same `schema.json` the core publishes
    (regenerated by `just update-schema`), never a hand-maintained copy.
"""

import functools
import json
import pathlib
from typing import Any

import rendercv


def repository_root() -> pathlib.Path:
    """Locate the repository root via the installed (editable) rendercv package.

    Why:
        Deriving the root from `rendercv.__file__` -- rather than this file's
        own location -- keeps this module correct regardless of where
        `rendercv_web` itself is packaged or vendored from.

    Returns:
        Absolute path to the repository root (the directory containing
        `schema.json` and `src/rendercv/`).
    """
    return pathlib.Path(rendercv.__file__).resolve().parent.parent.parent


@functools.lru_cache(maxsize=1)
def load_schema() -> dict[str, Any]:
    """Load and cache the repository's root JSON Schema file.

    Returns:
        Parsed JSON Schema document.

    Raises:
        FileNotFoundError: If `schema.json` is missing (run `just update-schema`).
    """
    schema_path = repository_root() / "schema.json"
    return json.loads(schema_path.read_text(encoding="utf-8"))
