/**
 * Shape of `static/wasm/manifest.json`, generated by
 * `scripts/build-wasm-assets.mjs`. Single source of truth for exact
 * filenames/versions so the engine code never hardcodes them redundantly.
 */
export interface WasmManifest {
	generatedAt: string;
	/** Path (relative to `/wasm/`) to the built rendercv wheel. */
	wheel: string;
	rendercvPackageVersion: string;
	fontawesomePackageVersion: string;
	/** Paths (relative to `/wasm/`) to the bundled font files. */
	fonts: string[];
	/** Path (relative to `/wasm/`) to the typst.ts web-compiler wasm binary. */
	typstCompilerWasm: string;
}

/**
 * Fetches the manifest written by `build:wasm-assets`.
 *
 * Why this can fail in an ordinary dev/CI checkout: the manifest (and
 * everything else under `static/wasm/`) is generated, not committed --
 * `npm run build:wasm-assets` must run at least once first. Callers should
 * treat a fetch failure here the same as any other engine-init failure (the
 * feature flag stays off by default, so this never blocks anyone who
 * hasn't opted in).
 */
export async function loadWasmManifest(
	baseUrl: string,
	fetchImpl: typeof fetch = fetch
): Promise<WasmManifest> {
	const response = await fetchImpl(`${baseUrl}/wasm/manifest.json`);
	if (!response.ok) {
		throw new Error(`Failed to load /wasm/manifest.json: HTTP ${response.status}`);
	}
	return (await response.json()) as WasmManifest;
}
