import { writable } from 'svelte/store';

/** The four YAML documents that make up a single CV, as raw text. */
export type DocumentKey = 'cv' | 'design' | 'locale' | 'settings';

export const DOCUMENT_KEYS: DocumentKey[] = ['cv', 'design', 'locale', 'settings'];

export const DOCUMENT_LABELS: Record<DocumentKey, string> = {
	cv: 'CV',
	design: 'Design',
	locale: 'Locale',
	settings: 'Settings'
};

export interface CvDocuments {
	cv: string;
	design: string;
	locale: string;
	settings: string;
}

/**
 * Placeholder content, shown for the moment before bootstrap loads a CV.
 *
 * Why it is deliberately minimal, and no longer a copy of the server's
 * starter CV: the real starter is generated by the backend from the core's
 * own sample (`rendercv_web/defaults.py`) and arrives from
 * `POST /api/cvs`. Those four documents run to roughly 350 lines between
 * them, and duplicating that here would be 350 lines kept in step by hand
 * across a language boundary -- guaranteed to drift, for no gain. This only
 * has to be renderable enough that the panes are not empty while the
 * request is in flight.
 */
export function createDefaultDocuments(): CvDocuments {
	return {
		cv: 'cv:\n  name: John Doe\n  sections: {}\n',
		design: '',
		locale: '',
		settings: 'settings:\n  pdf_title: NAME - CV\n'
	};
}

/**
 * The single source of truth for the four CV documents.
 *
 * Why: the form editor (later phases) and the YAML editor are two views of
 * this same store — never two copies that can diverge.
 */
export const documents = writable<CvDocuments>(createDefaultDocuments());

/** Replaces the text of a single document, leaving the others untouched. */
export function setDocument(key: DocumentKey, value: string): void {
	documents.update((docs) => ({ ...docs, [key]: value }));
}

/** Resets all four documents back to their defaults. */
export function resetDocuments(): void {
	documents.set(createDefaultDocuments());
}
