import type { JsonSchemaDocument } from './types';

let cached: JsonSchemaDocument | null = null;
let inFlight: Promise<JsonSchemaDocument> | null = null;

/**
 * Fetches `/api/schema` (the repository's `schema.json`, regenerated by
 * `just update-schema`) and caches it for the session.
 *
 * Why cache: the schema is static for the lifetime of a page load (it
 * describes the pydantic models, not user data) and every schema-driven
 * component needs it, so fetching once avoids a request storm on mount.
 */
export async function fetchSchema(
	fetchImpl: typeof fetch = fetch,
	options: { force?: boolean } = {}
): Promise<JsonSchemaDocument> {
	if (cached && !options.force) return cached;
	if (inFlight && !options.force) return inFlight;

	inFlight = (async () => {
		const response = await fetchImpl('/api/schema');
		if (!response.ok) {
			throw new Error(`GET /api/schema failed with status ${response.status}`);
		}
		const body = (await response.json()) as JsonSchemaDocument;
		cached = body;
		return body;
	})();

	try {
		return await inFlight;
	} finally {
		inFlight = null;
	}
}

/** Clears the cached schema (tests only). */
export function resetSchemaCache(): void {
	cached = null;
	inFlight = null;
}
